import {
  BookOpen,
  Calendar,
  DollarSign,
  MessageCircle,
  CalendarIcon,
  Users,
  Zap,
  BarChart3,
  Target,
  Briefcase,
  TrendingUp,
  LucideIcon,
} from "lucide-react";

export interface Testimonial {
  id: string;
  quote: string;
  author: string;
  role: string;
  company: string;
  image?: string; // Optional if you want to include author images
}

export const testimonials: Testimonial[] = [
  {
    id: "1",
    quote:
      "Empecé dando clases online y ahora tengo una comunidad que me da ingresos todos los meses. WeMany cambió el juego.",
    author: "Sofía Moreno",
    role: "Coach de Yoga",
    company: "Southside Wellness",
  },
  {
    id: "2",
    quote: "This is another great testimonial from a happy user.",
    author: "Jane Doe",
    role: "Fitness Instructor",
    company: "FitLife Studio",
  },
  {
    id: "3",
    quote: "My business grew significantly after using their platform.",
    author: "John Smith",
    role: "Personal Trainer",
    company: "GymPro",
  },
  {
    id: "4",
    quote: "Highly recommend their services for anyone looking to scale.",
    author: "Emily White",
    role: "Wellness Coach",
    company: "Mindful Living",
  },
  {
    id: "5",
    quote: "A truly transformative experience for my online classes.",
    author: "David menta",
    role: "Yoga Teacher",
    company: "Inner Peace Yoga",
  },
];

export const feedPosts = [
  {
    id: 1,
    communityId: 1,
    communityName: "NEOMENTES Academy",
    communityAvatar: "/placeholder.svg?height=32&width=32",
    author: "Isabella Rodriguez",
    authorAvatar: "/placeholder.svg",
    authorLevel: 92,
    time: "2h",
    content:
      "🚀 Acabo de cerrar mi primera venta de $10K este mes! Los módulos de marketing realmente funcionan. Gracias a toda la comunidad por el apoyo 💪",
    likes: 234,
    comments: 45,
    shares: 12,
    isSponsored: true,
    isPremium: true,
    previewComments: [
      { author: "Carlos M.", content: "¡Increíble! ¿Qué estrategia usaste?" },
      { author: "Ana G.", content: "Motivación pura 🔥" },
      { author: "Javier P.", content: "Necesito esos tips urgente" },
    ],
  },
  {
    id: 2,
    communityId: 2,
    communityName: "FitLife Pro",
    communityAvatar: "/placeholder.svg?height=32&width=32",
    author: "Ana Martínez",
    authorAvatar: "/placeholder.svg",
    authorLevel: 88,
    time: "4h",
    content:
      "Transformación de 90 días de María 💪 De 85kg a 68kg con nuestro plan personalizado. ¡Los resultados hablan por sí solos!",
    image: "/placeholder.svg?height=300&width=400&text=Transformation",
    likes: 189,
    comments: 67,
    shares: 23,
    isSponsored: true,
    isPremium: true,
    previewComments: [
      { author: "María S.", content: "¡Gracias Ana! Cambió mi vida" },
      { author: "Luis R.", content: "Impresionante progreso" },
      { author: "Carmen L.", content: "¿Cuánto tiempo de gym al día?" },
    ],
  },
  {
    id: 3,
    communityId: 3,
    communityName: "CodeMasters",
    communityAvatar: "/placeholder.svg?height=32&width=32",
    author: "Miguel Torres",
    authorAvatar: "/placeholder.svg",
    authorLevel: 95,
    time: "6h",
    content:
      "🎯 Nuevo proyecto: App de delivery completa con React Native y Node.js. 40 horas de contenido paso a paso. ¿Quién se apunta?",
    likes: 156,
    comments: 89,
    shares: 34,
    isSponsored: false,
    isPremium: true,
    previewComments: [
      { author: "Pedro C.", content: "¡Yo me apunto! ¿Cuándo empezamos?" },
      { author: "Sofia M.", content: "Perfecto para mi portfolio" },
      { author: "Diego R.", content: "¿Incluye backend también?" },
    ],
  },
  {
    id: 4,
    communityId: 4,
    communityName: "GameHub Elite",
    communityAvatar: "/placeholder.svg?height=32&width=32",
    author: "Alex Gaming",
    authorAvatar: "/placeholder.svg",
    authorLevel: 87,
    time: "8h",
    content:
      "🏆 Torneo de Valorant este fin de semana! Premio: $5000 + coaching personalizado. Inscripciones abiertas hasta mañana.",
    likes: 445,
    comments: 123,
    shares: 67,
    isSponsored: true,
    isPremium: false,
    previewComments: [
      { author: "Gamer123", content: "¡Ya me inscribí! A por el premio" },
      { author: "ProPlayer", content: "¿Qué rank mínimo se necesita?" },
      { author: "TeamLeader", content: "Mi equipo está listo 🔥" },
    ],
  },
  {
    id: 5,
    communityId: 5,
    communityName: "English Mastery",
    communityAvatar: "/placeholder.svg?height=32&width=32",
    author: "Sarah Johnson",
    authorAvatar: "/placeholder.svg",
    authorLevel: 76,
    time: "12h",
    content:
      "🎯 Nuevo método para aprender inglés conversacional en 30 días. Mis estudiantes están viendo resultados increíbles con esta técnica.",
    likes: 89,
    comments: 34,
    shares: 12,
    isSponsored: false,
    isPremium: true,
    previewComments: [
      { author: "Student1", content: "¿Funciona para principiantes?" },
      { author: "Maria L.", content: "Necesito esto urgente para mi trabajo" },
      { author: "Carlos R.", content: "¿Incluye pronunciación?" },
    ],
  },
  {
    id: 6,
    communityId: 6,
    communityName: "Crypto Traders",
    communityAvatar: "/placeholder.svg?height=32&width=32",
    author: "Roberto Crypto",
    authorAvatar: "/placeholder.svg",
    authorLevel: 89,
    time: "1d",
    content:
      "📈 Bitcoin rompió resistencia clave en $45K. Análisis técnico completo y próximos niveles a vigilar. Portfolio actualizado.",
    image: "/placeholder.svg?height=300&width=400&text=Bitcoin+Chart",
    likes: 234,
    comments: 78,
    shares: 45,
    isSponsored: true,
    isPremium: true,
    previewComments: [
      { author: "Trader123", content: "¿Cuál es tu target para BTC?" },
      { author: "InvestorPro", content: "Excelente análisis como siempre" },
      { author: "CryptoFan", content: "¿Altcoins también subirán?" },
    ],
  },
  {
    id: 7,
    communityId: 1,
    communityName: "NEOMENTES Academy",
    communityAvatar: "/placeholder.svg?height=32&width=32",
    author: "Carlos Rodríguez",
    authorAvatar: "/placeholder.svg",
    authorLevel: 98,
    time: "2d",
    content:
      "🔥 Nuevo módulo disponible: 'Automatización con IA para E-commerce'. Aprende a usar ChatGPT y herramientas IA para escalar tu negocio.",
    likes: 456,
    comments: 123,
    shares: 89,
    isSponsored: false,
    isPremium: true,
    previewComments: [
      { author: "Entrepreneur1", content: "¡Justo lo que necesitaba!" },
      { author: "AIFan", content: "¿Incluye prompts específicos?" },
      { author: "Scaler", content: "Perfecto timing para mi negocio" },
    ],
  },
  {
    id: 8,
    communityId: 2,
    communityName: "FitLife Pro",
    communityAvatar: "/placeholder.svg?height=32&width=32",
    author: "Ana Martínez",
    authorAvatar: "/placeholder.svg",
    authorLevel: 85,
    time: "3d",
    content:
      "💪 Rutina HIIT de 15 minutos que quema más calorías que 1 hora de cardio tradicional. Perfecta para personas ocupadas.",
    image: "/placeholder.svg?height=300&width=400&text=HIIT+Workout",
    likes: 178,
    comments: 56,
    shares: 34,
    isSponsored: true,
    isPremium: false,
    previewComments: [
      { author: "FitMom", content: "¡Perfecto para mi horario!" },
      { author: "BusyDad", content: "¿Se puede hacer en casa?" },
      { author: "HealthyLife", content: "Necesito esto en mi rutina" },
    ],
  },
];

export interface Lesson {
  id: string;
  title: string;
  description: string;
  duration: string;
  thumbnail: string;
  videoUrl: string;
  completed: boolean;
  isPlaying?: boolean;
  type: "video" | "live" | "document";
  hasAttachments: boolean;
}

export const lessons: Lesson[] = [
  {
    id: "1",
    title: "Introducción al E-commerce 2025",
    description: "Fundamentos básicos del comercio electrónico moderno",
    duration: "12:45",
    thumbnail: "/placeholder.svg?height=80&width=120&text=Intro+E-commerce",
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    completed: true,
    isPlaying: true,
    type: "live",
    hasAttachments: true,
  },
  {
    id: "2",
    title: "Configuración de tu Primera Tienda",
    description: "Aprende a configurar tu tienda desde cero",
    duration: "18:32",
    thumbnail: "/placeholder.svg?height=80&width=120&text=Config+Tienda",
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    completed: true,
    type: "video",
    hasAttachments: false,
  },
  {
    id: "3",
    title: "Selección de Productos Ganadores",
    description: "Cómo elegir productos que realmente vendan",
    duration: "24:18",
    thumbnail: "/placeholder.svg?height=80&width=120&text=Productos+Ganadores",
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    completed: false,
    type: "video",
    hasAttachments: true,
  },
  {
    id: "4",
    title: "Optimización de Páginas de Producto",
    description: "Mejora la conversión de tus páginas",
    duration: "16:55",
    thumbnail: "/placeholder.svg?height=80&width=120&text=Optimización+Páginas",
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    completed: false,
    type: "video",
    hasAttachments: false,
  },
  {
    id: "5",
    title: "Estrategias de Marketing Digital",
    description: "Promociona tu tienda efectivamente",
    duration: "22:10",
    thumbnail: "/placeholder.svg?height=80&width=120&text=Marketing+Digital",
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    completed: false,
    type: "video",
    hasAttachments: true,
  },
  {
    id: "6",
    title: "Análisis de Métricas y KPIs",
    description: "Mide el éxito de tu negocio",
    duration: "19:45",
    thumbnail: "/placeholder.svg?height=80&width=120&text=Métricas+KPIs",
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    completed: false,
    type: "video",
    hasAttachments: false,
  },
];

export const sampleData = {
  user: {
    name: "Isabella Rodriguez",
    username: "@isabella_ecom",
    avatar: "/placeholder.svg",
    level: 92,
    xp: 45680,
    nextLevelXp: 50000,
    streak: 47,
    ranking: 1,
    weeklyXp: 2450,
  },

  communities: [
    {
      id: 1,
      name: "NEOMENTES Academy",
      description: "La comunidad #1 de e-commerce en español",
      members: 2847,
      category: "E-commerce",
      image: "/community-banner-ecommerce-neomentes.png",
      isJoined: true,
      role: "Fundador",
      xp: 15420,
      maxXp: 20000,
      progress: 77,
      badges: ["Fundador", "Top Contributor"],
      color: "from-purple-500 to-blue-500",
    },
    {
      id: 2,
      name: "Dropshipping Masters",
      description: "Estrategias avanzadas de dropshipping",
      members: 1240,
      category: "Dropshipping",
      image: "/placeholder.svg?height=200&width=400&text=Dropshipping",
      isJoined: true,
      role: "Mentor VIP",
      xp: 8950,
      maxXp: 10000,
      progress: 89,
      badges: ["Mentor", "Expert"],
      color: "from-green-500 to-emerald-500",
    },
    {
      id: 3,
      name: "E-commerce Elite",
      description: "Red exclusiva de top performers",
      members: 890,
      category: "Elite",
      image: "/placeholder.svg?height=200&width=400&text=Elite",
      isJoined: false,
      role: "Top Performer",
      xp: 12300,
      maxXp: 15000,
      progress: 82,
      badges: ["Elite", "High Performer"],
      color: "from-orange-500 to-red-500",
    },
  ],

  events: [
    {
      id: 1,
      title: "Masterclass: Scaling to 7 Figures",
      instructor: "Isabella Rodriguez",
      instructorAvatar: "/placeholder.svg",
      date: "2024-01-20",
      time: "19:00",
      duration: "2h",
      attendees: 847,
      maxAttendees: 1000,
      category: "Masterclass",
      isLive: false,
      isPremium: true,
      thumbnail: "/images/video-thumbnail.png",
      description:
        "Aprende las estrategias exactas que usé para escalar mi negocio de e-commerce a 7 cifras en 18 meses.",
    },
    {
      id: 2,
      title: "Q&A Session: Facebook Ads 2024",
      instructor: "Carlos Mendoza",
      instructorAvatar: "/placeholder.svg",
      date: "2024-01-18",
      time: "20:00",
      duration: "1h 30m",
      attendees: 234,
      maxAttendees: 500,
      category: "Q&A",
      isLive: true,
      isPremium: false,
      thumbnail: "/placeholder.svg?height=200&width=400&text=Facebook+Ads",
      description:
        "Sesión de preguntas y respuestas sobre las últimas estrategias de Facebook Ads.",
    },
  ],

  modules: [
    {
      id: 1,
      title: "Fundamentos del E-commerce",
      description:
        "Aprende los conceptos básicos para iniciar tu negocio online",
      progress: 85,
      totalLessons: 12,
      completedLessons: 10,
      duration: "4h 30m",
      difficulty: "Principiante",
      category: "Fundamentos",
      instructor: "Isabella Rodriguez",
      rating: 4.9,
      students: 1247,
      thumbnail: "/placeholder.svg?height=200&width=300&text=E-commerce+Basics",
      isCompleted: false,
      isPremium: false,
    },
    {
      id: 2,
      title: "Estrategias de Marketing Digital",
      description:
        "Domina las técnicas más efectivas para promocionar tu negocio",
      progress: 60,
      totalLessons: 15,
      completedLessons: 9,
      duration: "6h 15m",
      difficulty: "Intermedio",
      category: "Marketing",
      instructor: "Ana Gutierrez",
      rating: 4.8,
      students: 892,
      thumbnail: "/placeholder.svg?height=200&width=300&text=Digital+Marketing",
      isCompleted: false,
      isPremium: true,
    },
    {
      id: 3,
      title: "Automatización y Scaling",
      description: "Escala tu negocio con sistemas automatizados",
      progress: 100,
      totalLessons: 10,
      completedLessons: 10,
      duration: "5h 45m",
      difficulty: "Avanzado",
      category: "Scaling",
      instructor: "Isabella Rodriguez",
      rating: 5.0,
      students: 456,
      thumbnail: "/placeholder.svg?height=200&width=300&text=Automation",
      isCompleted: true,
      isPremium: true,
    },
  ],

  leaderboard: [
    {
      rank: 1,
      name: "Isabella Rodriguez",
      username: "@isabella_ecom",
      avatar: "/placeholder.svg",
      xp: 45680,
      weeklyXp: 2450,
      level: 92,
      badges: ["👑", "🔥", "⭐"],
      trend: "up",
    },
    {
      rank: 2,
      name: "Carlos Mendoza",
      username: "@carlos_ads",
      avatar: "/placeholder.svg",
      xp: 42150,
      weeklyXp: 1890,
      level: 89,
      badges: ["🚀", "💎", "🎯"],
      trend: "up",
    },
    {
      rank: 3,
      name: "Ana Gutierrez",
      username: "@ana_marketing",
      avatar: "/placeholder.svg",
      xp: 38920,
      weeklyXp: 1650,
      level: 85,
      badges: ["📈", "✨", "🏆"],
      trend: "down",
    },
    {
      rank: 4,
      name: "Miguel Torres",
      username: "@miguel_growth",
      avatar: "/placeholder.svg",
      xp: 35670,
      weeklyXp: 1420,
      level: 82,
      badges: ["🎪", "🌟", "🔥"],
      trend: "up",
    },
    {
      rank: 5,
      name: "Sofia Chen",
      username: "@sofia_design",
      avatar: "/placeholder.svg",
      xp: 33240,
      weeklyXp: 1280,
      level: 79,
      badges: ["🎨", "💫", "🚀"],
      trend: "same",
    },
  ],

  posts: [
    {
      id: 1,
      author: "Isabella Rodriguez",
      username: "@isabella_ecom",
      avatar: "/placeholder.svg",
      timestamp: "hace 2 horas",
      content:
        "¡Increíble! Acabamos de superar los $2.8M en ventas verificadas este año. El poder de la comunidad y la educación de calidad es real. 🚀💎",
      likes: 234,
      comments: 45,
      shares: 12,
      isLiked: false,
      badges: ["👑", "🔥"],
      community: "NEOMENTES Academy",
    },
    {
      id: 2,
      author: "Carlos Mendoza",
      username: "@carlos_ads",
      avatar: "/placeholder.svg",
      timestamp: "hace 4 horas",
      content:
        "Nuevo video tutorial sobre Facebook Ads 2024 disponible en el módulo premium. Las estrategias que están funcionando AHORA mismo 📈",
      likes: 156,
      comments: 28,
      shares: 8,
      isLiked: true,
      badges: ["🚀", "💎"],
      community: "Dropshipping Masters",
    },
  ],

  battlePass: {
    currentLevel: 92,
    currentXp: 45680,
    nextLevelXp: 50000,
    progress: 91,
    rewards: [
      { level: 95, reward: "Avatar Frame Dorado", unlocked: false },
      { level: 100, reward: "Acceso VIP Exclusivo", unlocked: false },
      { level: 105, reward: "Mentoría 1:1 con Isabella", unlocked: false },
    ],
  },
};

export interface AvailableMilestones {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  type: "count" | "amount" | "duration" | "ratio";
  plugin: string;
  pluginName: string;
}

export const availableMilestones: AvailableMilestones[] = [
  // WeMany Internal Plugin
  {
    id: "modules_completed",
    name: "Módulos Completados",
    description: "Número de módulos completados por el usuario",
    icon: BookOpen,
    type: "count",
    plugin: "wemany_internal",
    pluginName: "WeMany Internal",
  },
  {
    id: "consecutive_months",
    name: "Meses Consecutivos",
    description: "Meses consecutivos como miembro activo",
    icon: Calendar,
    type: "duration",
    plugin: "wemany_internal",
    pluginName: "WeMany Internal",
  },
  {
    id: "posts_created",
    name: "Posts Creados",
    description: "Número de posts creados en la comunidad",
    icon: MessageCircle,
    type: "count",
    plugin: "wemany_internal",
    pluginName: "WeMany Internal",
  },
  {
    id: "events_attended",
    name: "Eventos Asistidos",
    description: "Número de eventos a los que ha asistido",
    icon: CalendarIcon,
    type: "count",
    plugin: "wemany_internal",
    pluginName: "WeMany Internal",
  },
  {
    id: "referrals_made",
    name: "Referencias Hechas",
    description: "Número de personas referidas a la comunidad",
    icon: Users,
    type: "count",
    plugin: "wemany_internal",
    pluginName: "WeMany Internal",
  },
  {
    id: "total_xp",
    name: "Experiencia Total",
    description: "Puntos de experiencia acumulados",
    icon: Zap,
    type: "count",
    plugin: "wemany_internal",
    pluginName: "WeMany Internal",
  },
  // Shopify Plugin
  {
    id: "shopify_sales",
    name: "Ventas en Shopify",
    description: "Monto total de ventas en Shopify",
    icon: DollarSign,
    type: "amount",
    plugin: "shopify_api",
    pluginName: "Shopify",
  },
  {
    id: "shopify_orders",
    name: "Órdenes en Shopify",
    description: "Número total de órdenes procesadas",
    icon: Briefcase,
    type: "count",
    plugin: "shopify_api",
    pluginName: "Shopify",
  },
  {
    id: "shopify_products",
    name: "Productos Creados",
    description: "Número de productos creados en Shopify",
    icon: Target,
    type: "count",
    plugin: "shopify_api",
    pluginName: "Shopify",
  },
  // Facebook Ads Plugin
  {
    id: "facebook_ads_spend",
    name: "Gasto en Facebook Ads",
    description: "Monto total gastado en publicidad de Facebook",
    icon: BarChart3,
    type: "amount",
    plugin: "facebook_api",
    pluginName: "Facebook Ads",
  },
  {
    id: "facebook_campaigns",
    name: "Campañas Creadas",
    description: "Número de campañas publicitarias creadas",
    icon: Target,
    type: "count",
    plugin: "facebook_api",
    pluginName: "Facebook Ads",
  },
  {
    id: "facebook_roas",
    name: "ROAS Promedio",
    description: "Retorno de inversión publicitaria promedio",
    icon: TrendingUp,
    type: "ratio",
    plugin: "facebook_api",
    pluginName: "Facebook Ads",
  },
  // Google Analytics Plugin
  {
    id: "ga_sessions",
    name: "Sesiones en GA",
    description: "Número de sesiones en Google Analytics",
    icon: BarChart3,
    type: "count",
    plugin: "google_analytics",
    pluginName: "Google Analytics",
  },
  {
    id: "ga_conversions",
    name: "Conversiones",
    description: "Número de conversiones registradas",
    icon: Target,
    type: "count",
    plugin: "google_analytics",
    pluginName: "Google Analytics",
  },
];
