import { Analytics } from '@vercel/analytics/next';
import type { Metadata } from "next";
import "./globals.css";
import {
  openSauceTwo,
  jetBrainsMono,
  radioCanadaBig,
} from '../lib/fonts';
export const metadata: Metadata = {
  title: {
    template: '%s | Mi App',
    default: 'Mi App',
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSauceTwo.variable} ${jetBrainsMono.variable} ${radioCanadaBig.variable} bg-gray-950 text-white`}>
        {children}
        <Analytics />

      </body>
    </html>
  );
}
